# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09e95b9f06309d7c282bedfbe3dff46917cf3e72d4b0ea2eee6b9ee6adc1e95b8d1bd8f4f237307e58486c7a382800b3787d30db9ec3f3d0733f41ea5f61a903

test:
  secret_key_base: 0c3bb6ff242a9f745bf7b06cfdb2af9b3a80135dff4bf97c4cf4e16572f63fa5ecd4321be59282c115d31ad34d2a47f5b02d94ee3ef3c9fccc0fb04128a7fcaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
